[package]
name = "rgb-interfaces"
version = "0.11.0-beta.7"
description = "Collection of the standard RGB smart contract interface"
keywords = ["bitcoin", "lightning", "rgb", "smart-contracts", "lnp-bp"]
categories = ["cryptography::cryptocurrencies"]
authors = ["Dr Maxim Orlovsky <orlovsky@lnp-bp.org>"]
homepage = "https://github.com/RGB-WG"
repository = "https://github.com/RGB-WG/rgb-interfaces"
rust-version = "1.76.0"  # rgb-std
edition = "2021"
license = "Apache-2.0"
readme = "README.md"

[[bin]]
name = "rgb-interfaces"
required-features = ["fs"]

[lib]
name = "ifaces"

[dependencies]
amplify = "4.7.0"
strict_encoding = "2.7.0-rc.1"
strict_types = "2.7.0-rc.1"
aluvm = "0.11.0-beta.7"
bp-core = "0.11.0-beta.7"
chrono = "0.4.38"
rgb-std = { version = "0.11.0-beta.7" }
serde_crate = { package = "serde", version = "1.0", optional = true }
serde_json = "1.0"
sha2 = "0.10.8"

[features]
default = []
all = ["serde", "fs"]
serde = ["serde_crate", "rgb-std/serde", "chrono/serde"]
fs = ["rgb-std/fs"]
